CONTIKI_PROJECT = my_border
all: $(CONTIKI_PROJECT)

CONTIKI = ../..

#use this to enable TSCH: MAKE_MAC = MAKE_MAC_TSCH
#AKE_MAC ?= MAKE_MAC_CSMA
#MAKE_NET = MAKE_NET_NULLNET
include $(CONTIKI)/Makefile.include
